id: A6343A3DD
base_file: f01D8.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:32:13.856724
  last_modified_at: 2022-05-30 20:32:13.856731
