id: A6343A3DD
base_file: f8709.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:32:13.861345
  last_modified_at: 2022-05-30 20:32:13.861350
